CREATE DATABASE VICENS_BD
GO
USE VICENS_BD
GO
/****** Object:  Table [dbo].[PAISES]    Script Date: 09/21/2018 18:32:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE[dbo].[PAISES](
    [IDPAIS][int] IDENTITY(1, 1) NOT NULL,
    [NOMBRE][varchar](50) NOT NULL,
    PRIMARY KEY CLUSTERED
        (
        [IDPAIS] ASC
        )WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
) ON[PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT[dbo].[PAISES] ON
INSERT[dbo].[PAISES]([IDPAIS], [NOMBRE]) VALUES(1, N'ARGENTINA')
SET IDENTITY_INSERT[dbo].[PAISES] OFF
/****** Object:  Table [dbo].[MARCAS]    Script Date: 09/21/2018 18:32:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE[dbo].[MARCAS](
    [IDMARCA][int] NOT NULL,
    [DESCRIPCION][varchar](50) NOT NULL,
    [ESTADO][bit] NOT NULL,
    PRIMARY KEY CLUSTERED
        (
        [IDMARCA] ASC
        )WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY],
    UNIQUE NONCLUSTERED
        (
        [DESCRIPCION] ASC
        )WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
) ON[PRIMARY]
GO
SET ANSI_PADDING OFF
GO
INSERT[dbo].[MARCAS]([IDMARCA], [DESCRIPCION], [ESTADO]) VALUES(1, N'LENOVO', 1)
INSERT[dbo].[MARCAS]([IDMARCA], [DESCRIPCION], [ESTADO]) VALUES(2, N'DELL', 1)
/****** Object:  Table [dbo].[CATEGORIAS]    Script Date: 09/21/2018 18:32:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE[dbo].[CATEGORIAS](
    [IDCATEGORIA][int] IDENTITY(1, 1) NOT NULL,
    [CATEGORIA][varchar](30) NOT NULL,
    [ESTADO][bit] NOT NULL,
    PRIMARY KEY CLUSTERED
        (
        [IDCATEGORIA] ASC
        )WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
) ON[PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PROVINCIAS]    Script Date: 09/21/2018 18:32:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE[dbo].[PROVINCIAS](
    [IDPROVINCIA][int] IDENTITY(1, 1) NOT NULL,
    [NOMBRE][varchar](50) NULL,
    [IDPAIS][int] NOT NULL,
    PRIMARY KEY CLUSTERED
        (
        [IDPROVINCIA] ASC
        )WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
) ON[PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT[dbo].[PROVINCIAS] ON
INSERT[dbo].[PROVINCIAS]([IDPROVINCIA], [NOMBRE], [IDPAIS]) VALUES(3, N'Buenos Aires', 1)
INSERT[dbo].[PROVINCIAS]([IDPROVINCIA], [NOMBRE], [IDPAIS]) VALUES(4, N'Rosario', 1)
INSERT[dbo].[PROVINCIAS]([IDPROVINCIA], [NOMBRE], [IDPAIS]) VALUES(5, N'Cordoba', 1)
INSERT[dbo].[PROVINCIAS]([IDPROVINCIA], [NOMBRE], [IDPAIS]) VALUES(6, N'Mendoza', 1)
SET IDENTITY_INSERT[dbo].[PROVINCIAS] OFF
/****** Object:  Table [dbo].[LOCALIDADES]    Script Date: 09/21/2018 18:32:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE[dbo].[LOCALIDADES](
    [IDLOCALIDAD][int] NOT NULL,
    [NOMBRE][varchar](50) NOT NULL,
    [IDPROVINCIA][int] NOT NULL,
    PRIMARY KEY CLUSTERED
        (
        [IDLOCALIDAD] ASC
        )WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
) ON[PRIMARY]
GO
SET ANSI_PADDING OFF
GO
INSERT[dbo].[LOCALIDADES]([IDLOCALIDAD], [NOMBRE], [IDPROVINCIA]) VALUES(1617, N'Gral. Pacheco', 3)
INSERT[dbo].[LOCALIDADES]([IDLOCALIDAD], [NOMBRE], [IDPROVINCIA]) VALUES(1644, N'San Fernando', 3)
/****** Object:  Table [dbo].[CLIENTES]    Script Date: 09/21/2018 18:32:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE[dbo].[CLIENTES](
    [IDCLIENTE][int] IDENTITY(1, 1) NOT NULL,
    [DNI][int] NOT NULL,
    [NOMBRE][varchar](50) NOT NULL,
    [APELLIDO][varchar](50) NOT NULL,
    [FNAC][datetime] NOT NULL,
    [CALLE][varchar](50) NOT NULL,
    [SEXO][varchar](10) NOT NULL,
    [IDLOCALIDAD][int] NOT NULL,
    [ESTADO][bit] NOT NULL,
    PRIMARY KEY CLUSTERED
        (
        [IDCLIENTE] ASC
        )WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY],
    UNIQUE NONCLUSTERED
        (
        [DNI] ASC
        )WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
) ON[PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT[dbo].[CLIENTES] ON
INSERT[dbo].[CLIENTES]([IDCLIENTE], [DNI], [NOMBRE], [APELLIDO], [FNAC], [CALLE], [SEXO], [IDLOCALIDAD], [ESTADO]) VALUES(1, 17057979, N'BETY', N'PAVON', CAST(0x00005C0500000000 AS DateTime), N'CUBA 621', N'FEMENINO', 1617, 1)
INSERT[dbo].[CLIENTES]([IDCLIENTE], [DNI], [NOMBRE], [APELLIDO], [FNAC], [CALLE], [SEXO], [IDLOCALIDAD], [ESTADO]) VALUES(3, 39912107, N'SABRINA', N'TRUPPEL', CAST(0x00008A0600000000 AS DateTime), N'DEBENEDETTI 24', N'FEMENINO', 1644, 1)
SET IDENTITY_INSERT[dbo].[CLIENTES] OFF
/****** Object:  Table [dbo].[PROVEEDORES]    Script Date: 09/21/2018 18:32:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE[dbo].[PROVEEDORES](
    [IDPROVEEDOR][int] IDENTITY(1, 1) NOT NULL,
    [CUIT][varchar](20) NOT NULL,
    [DESCRIPCION][varchar](50) NOT NULL,
    [DIRECCION][varchar](50) NOT NULL,
    [IDLOCALIDAD][int] NOT NULL,
    [TELEFONO][varchar](50) NULL,
    [MAIL][varchar](50) NULL,
    [ESTADO][bit] NOT NULL,
    PRIMARY KEY CLUSTERED
        (
        [IDPROVEEDOR] ASC
        )WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY],
    UNIQUE NONCLUSTERED
        (
        [DESCRIPCION] ASC
        )WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY],
    UNIQUE NONCLUSTERED
        (
        [CUIT] ASC
        )WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
) ON[PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT[dbo].[PROVEEDORES] ON
INSERT[dbo].[PROVEEDORES]([IDPROVEEDOR], [CUIT], [DESCRIPCION], [DIRECCION], [IDLOCALIDAD], [TELEFONO], [MAIL], [ESTADO]) VALUES(2, N'20340094434', N'NADA', N'ECUADOR 621', 1617, N'47405465', N'SEBA@GMAIL', 1)
SET IDENTITY_INSERT[dbo].[PROVEEDORES] OFF
/****** Object:  Table [dbo].[ARTICULOS]    Script Date: 09/21/2018 18:32:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE[dbo].[ARTICULOS](
    [IDARTICULO][int] IDENTITY(1, 1) NOT NULL,
    [DESCRIPCION][varchar](50) NOT NULL,
    [IDMARCA][int] NOT NULL,
    [IDPROVEEDOR][int] NOT NULL,
    [ORIGEN][varchar](50) NULL,
    [STOCK][int] NOT NULL,
    [PU][money] NOT NULL,
    [PUCOMPRA][money] NOT NULL,
    [ESTADO][bit] NOT NULL,
    CONSTRAINT[PK_AxP] PRIMARY KEY CLUSTERED
        (
        [IDARTICULO] ASC
        )WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY],
    UNIQUE NONCLUSTERED
        (
        [DESCRIPCION] ASC
        )WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
) ON[PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT[dbo].[ARTICULOS] ON
INSERT[dbo].[ARTICULOS]([IDARTICULO], [DESCRIPCION], [IDMARCA], [IDPROVEEDOR], [ORIGEN], [STOCK], [PU], [PUCOMPRA], [ESTADO]) VALUES(4, N'NOTEBOOK', 1, 2, N'CHINA', 100, 10000.0000, 5000.0000, 1)
SET IDENTITY_INSERT[dbo].[ARTICULOS] OFF
/****** Object:  Table [dbo].[CATEGORIAS_X_ARTICULO]    Script Date: 09/21/2018 18:32:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE[dbo].[CATEGORIAS_X_ARTICULO](
    [IDARTICULO][int] NOT NULL,
    [IDCATEGORIA][int] NOT NULL,
    PRIMARY KEY CLUSTERED
        (
        [IDARTICULO] ASC,
        [IDCATEGORIA] ASC
        )WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
) ON[PRIMARY]
GO
/****** Object:  Check [CK__ARTICULOS__STOCK__4222D4EF]    Script Date: 09/21/2018 18:32:37 ******/
ALTER TABLE[dbo].[ARTICULOS]  WITH CHECK ADD CHECK(([STOCK] >= (0)))
GO
/****** Object:  ForeignKey [FK__ARTICULOS__IDMAR__403A8C7D]    Script Date: 09/21/2018 18:32:37 ******/
ALTER TABLE[dbo].[ARTICULOS]  WITH CHECK ADD FOREIGN KEY([IDMARCA])
REFERENCES[dbo].[MARCAS]([IDMARCA])
GO
/****** Object:  ForeignKey [FK__ARTICULOS__IDPRO__412EB0B6]    Script Date: 09/21/2018 18:32:37 ******/
ALTER TABLE[dbo].[ARTICULOS]  WITH CHECK ADD FOREIGN KEY([IDPROVEEDOR])
REFERENCES[dbo].[PROVEEDORES]([IDPROVEEDOR])
GO
/****** Object:  ForeignKey [FK__CATEGORIA__IDART__5629CD9C]    Script Date: 09/21/2018 18:32:37 ******/
ALTER TABLE[dbo].[CATEGORIAS_X_ARTICULO]  WITH CHECK ADD FOREIGN KEY([IDARTICULO])
REFERENCES[dbo].[ARTICULOS]([IDARTICULO])
GO
/****** Object:  ForeignKey [FK__CATEGORIA__IDCAT__571DF1D5]    Script Date: 09/21/2018 18:32:37 ******/
ALTER TABLE[dbo].[CATEGORIAS_X_ARTICULO]  WITH CHECK ADD FOREIGN KEY([IDCATEGORIA])
REFERENCES[dbo].[CATEGORIAS]([IDCATEGORIA])
GO
/****** Object:  ForeignKey [FK__CLIENTES__IDLOCA__1DE57479]    Script Date: 09/21/2018 18:32:37 ******/
ALTER TABLE[dbo].[CLIENTES]  WITH CHECK ADD FOREIGN KEY([IDLOCALIDAD])
REFERENCES[dbo].[LOCALIDADES]([IDLOCALIDAD])
GO
/****** Object:  ForeignKey [FK__LOCALIDAD__IDPRO__09DE7BCC]    Script Date: 09/21/2018 18:32:37 ******/
ALTER TABLE[dbo].[LOCALIDADES]  WITH CHECK ADD FOREIGN KEY([IDPROVINCIA])
REFERENCES[dbo].[PROVINCIAS]([IDPROVINCIA])
GO
/****** Object:  ForeignKey [FK__PROVEEDOR__IDLOC__34C8D9D1]    Script Date: 09/21/2018 18:32:37 ******/
ALTER TABLE[dbo].[PROVEEDORES]  WITH CHECK ADD FOREIGN KEY([IDLOCALIDAD])
REFERENCES[dbo].[LOCALIDADES]([IDLOCALIDAD])
GO
/****** Object:  ForeignKey [FK__PROVINCIA__IDPAI__0519C6AF]    Script Date: 09/21/2018 18:32:37 ******/
ALTER TABLE[dbo].[PROVINCIAS]  WITH CHECK ADD FOREIGN KEY([IDPAIS])
REFERENCES[dbo].[PAISES]([IDPAIS])
GO
